# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.define "wordpress" do |wp|
      wp.vm.hostname = "wordpress"
      wp.vm.network "private_network", ip: "10.30.0.30"
      wp.vm.provision :shell, path: "install/install.sh"
  end
end
