VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |
	config.vm.box = "puphpet/centos65-x64"
	config.vm.define "gluster-server" do | server |
		server.vm.network :private_network, ip: "10.30.0.52"
		server.vm.hostname = "server"
	end
	config.vm.define "gluster-client" do |client|
		client.vm.network :private_network, ip: "10.30.0.53"
		client.vm.hostname =  "client"
	end
end
